---
title: "Understanding Species and Varietals"
date: "`r Sys.Date()`"
tags: 
- varietal
- basics
---

# Coffee Species And Varietals
&nbsp;<BR><BR>

{{< figure link="/img/worldatlascoffee.jpg" >}}


Picture Sourced from [James Hoffmann](https://www.jameshoffmann.co.uk/work#/coffee-family-tree-variety-timeline-poster/)


## Difficult Questions

Species and varietals are a complex subject. (But then, what isn’t?)

The problem isn’t just that there are more than 100 species of coffee and thousands of coffee varietals, with more being discovered or bred each year. The real challenge lies in the fact that genetic testing for coffee is not readily accessible to farmers. Since it is generally difficult to differentiate coffee species/varietals just by looking at them, misidentifications and misclassifications often occur.

For example, Pink Bourbon was initially believed to be a spontaneous mutation of the Bourbon varietal after being discovered growing among Bourbon plants on a farm. However, [recent genetic testing has shown that Pink Bourbon is not related to Bourbon at all.](https://www.cafeimports.com/north-america/blog/2023/09/26/pink-bourbon-cryptozoology-and-genetics-in-specialty-coffee/)

[One study](https://academic.oup.com/jaoac/article/103/2/325/5809455) showed that out of 88 Gesha variety samples collected in the World Coffee Research database, only 39% were an exact match with the Gesha reference, 24% were closely related to Gesha, and the remaining 37% were unrelated to Gesha (including SL34, Typica/Bourbon mix, etc.).

Many old text may indicate that SL34 is a 'Bourbon-related' coffee varietal. However, [a recent genetic test have shown that SL34 is actually closely related to Typica rather than Bourbon.](https://varieties.worldcoffeeresearch.org/varieties/sl34) 

Therefore, it’s important to recognize that what we currently know about coffee species and varietals is somewhat flawed and subject to change with more thorough research.

## Defining Species and Varietals

Rather than going all in on the biology textbook (Domain - Kingdom - Phylum ...), for this purpose, we are simply going to use 'dog' as a good reference.

The dog is a one of the species under genus "Canis." Many species of animals are part of "Canis" such as coyotes, wolves, and jackals. Even though all the dogs are part of the same species, they are further divided into breeds such as poodle, bulldog, husky, beagle, etc. For the purpose of simplification, breed is very similar to variety because it is used to further classify animals/plants under the same species.

## Coffee Species

While there are more than a hundred different species, most of cultivated coffee are either Arabica or Robusta. 

**Arabica** is the predominant species in the specialty coffee scene. When people refer to "Specialty Grade" coffee, they are typically talking about Arabica. Arabica is known for its expressive acidity and fruity notes. High-quality Arabica, in particular, tends to shine when roasted on the lighter end of the spectrum.

**Robusta** is the second most cultivated coffee species in the world. Although Robusta has historically been regarded as "second grade" compared to Arabica (with some products proudly labeling themselves as "100% Arabica"), it has recently surged in popularity for several reasons. Innovations in processing methods have shown that Robusta can produce high-quality coffee. Additionally, Robusta is highly resistant to major pests and diseases and thrives in harsh conditions. Many view Robusta as one of the important species to answer climate change. Unlike Arabica, Robusta typically excels in darker roasts.

**Liberica**, one of the minor species of coffee, has also been [gaining attention due to climate change.](https://www.nature.com/articles/s41477-022-01309-5) Liberica is mainly being researched to produce hybrid species that are resistant to climate change, pests, and diseases.

**Eugenioides**, another one of the minor species of coffee, was once abandoned and almost went extinct due to low yield. However, Eugenioides coffee gained [huge attention in 2016 for purpose of barista competition.](https://intelligence.coffee/2023/03/whatever-happened-eugenioides-coffee/) [One can watch Morgan Eckroth, 2022 USBC champion, explaining Eugenioides here.](https://www.youtube.com/watch?v=dd-IhDHn6tM)


## Coffee Varietals

When coffee varietals are discussed, it is almost always coffee varietals of Arabica coffee. While climate change increased interest for Robusta varietal research, we still don't have much information. Only recently world coffee research included information about Robusta varietals.

Aribica varietals can be divided into several groups : Ethiopian Landrace, Typica, Bourbon, Bourbon-Typica, F1 hybrid, Catimor, and Sachimor.

### Ethiopian Landrace

While there are some dissenting opinions, majority now agree that Ethiopia is the origin of Arabican coffee. (It is interesting to note that the name "Arabica" comes from the belief that the beans originated from the Arabian peninsula.) As the birthplace of Arabican coffee there are countless number of varietals that have yet to receive their own labels. Most Ethiopian farmers do not differentiate varietals. Coffee originated from Ethiopia is typically labeled as "Ethiopian Landrace" or "Ethiopian Heirloom" and they either mean large number of varietals are mixed together or it is a varietal that is yet to be properly identified. 

One of the most important Ethiopian Landrace is Gesha or Geisha varietal. Despite the "Geisha" name, its name has nothing to do with Japan. Gori Gesha forest, where the Gesha varietal originated from, used to be spelled as "Geisha." Originally labeled as T2722, Gesha coffee was grown in Panama Hacienda La Esmeralda for its disease-resistance. The farm discovered that it had distinct floral aroma at 2003 and submitted it to 2004 Best of Panama competition. Since then, Gesha varietals are now grown all over the world from Colombia and Guatemala to Taiwan. Gesha is considered one of the most expensive varietals of coffee.

### Typica

Typica is considered "one of the most culturally and genetically important" Arabican coffee in the world according to World Coffee Research and most arabican varietals are descendant of Typica or Bourbon. Despite this, Typica coffee has been losing ground in most of the world due to its low yield and high susceptibility to major diseases.

Few important Typica-descended varietals are Typica (sometimes labeled as Blue Mountain), SL34, and Maragogipe. Typica/Blue Mountain is cultivated in Jamaica, Papa New Guinea, and Peru. SL34 was selected by Scott Laboratories (hence the suffix SL) in Kenya and originally believed to be Bourbon-descended varietals. Alongside with SL28 and Ruiru, SL34 is considered one of the most important coffee varietal in Kenya. SL34 is also cultivated in other countries such as Costa Rica and Nicaragua. Maragogipe is a natural mutation of Typica varietal. While it is known to produce very high quality coffee, due to its low yield, many farmers seem to prefer Maragogipe's children Pacamara (Pacas and Maragogipe crossbreed) and Maracaturra (Caturra and Maragogipe corssbreed)

### Bourbon

It is one of the "other" 'one of the most culturally and genetically important' Arabican coffee in the world. French Missionaries introduced coffee beans to Bourbon Island (hence the name Bourbon) in the early 1700s. As the missionaries gained more influence in various parts of the Africa and America in mid-19th century, the Bourbon varietal began to spread. Bourbon and Bourbon-related varietals are especially important in Americas.

Few important Bourbon-descended varietals are Bourbon, SL28, Villa Sarchi, Pacas, and Caturra. SL28 is another varietal that was selected by Scott Laboratories and important varietal in Costa Rica and especially Kenya. 

Caturra and Villa Sarchi are natural mutations of Bourbon and they play important roles for developing disease-resistant coffee with potentially high yield. They were primarily selected for 'compact stature' and compact stature allowed for more dense farming and potential for increased yield. Caturra was crossbred with Timor Hybrid (Arabica - Robusta crossbreed with high disease resistance) to create "Catimor Group", was crossbred with Mundo Novo (Typica - Bourbon crossbreed) to create Catuai, and it was used to breed several F1 Hybrid (crossbreed with Ethiopian Landrace). Villa Sarchi was crossbred with Timor Hybrid to create Sachimor. 

### Bourbon-Typica Crossbreed

Bourbon and Typica varietals were the most commonly cultivated cultivars in the world. Many artificially crossbred Bourbon and Typica related varietals together and some happened naturally. 3 important Bourbon-Typica crossbreeds are Mundo Novo (Typica - Bourbon crossbreed), Catuai (Mundo Novo - Caturra crossbreed), and Pacamara (Pacas - Maragogipe crossbreed).

Catuai is particularly important as accounts for almost half of all Arabica production. While its quality is considered good but not great, its compact stature and high yield made it very economically viable. Pacamara is also important as it produces exceptional quality, high yield, and with large bean size. (There was a time when large bean size was considered high quality.) Sadly, Pacamara varietal has not fully stabilized and it is not stable from one generation to the next. Despite this, it is still grown in Central America such as El Salvador and Guatemala.

### F1 Hybrids

F1 Hybrids stand for first generation hybrids. Remember about Pacamara varietal not being fully stable one generation to the next? F1 Hybrids are the same. F1 Hybrids crossbreeds Ethipian Landrace and other varietals to produce varietals with significantly higher yields that can grow in low altitudes. Sometimes, it will outperform in quality, disease, wind, and/or frost tolerance. Despite many difficulties of F1 Hybrids, for some working with these varieties are worth the effort. The difficulties of F1 Hybrids may include requiring manual pollination (Ruiru 11, etc.) or clone propagation which is far more labor intensive comparative to planting coffee seeds (H3, Esparanza, etc.) It is also important to note that coffee quality, yield, disease resistance, etc. are dependent on many factors. For certain environment, farming technique, processing, etc. varietals that adjusted well to the local environment may perform better and F1 Hybrids shouldn't be treated like an upgrade.

Currently, the commercial use of F1 Hybrids is limited. However, more research is being done and F1 Hybrids are viewed as one of the potential solutions to climate change and various diseases.


### Catimor

As mentioned above, Catimor group was bred using Caturra and Timor Hybrid. As Caturra is one of the most popular Arabican coffee varietal, it was natural that many researchers decided to improve it by crossbreeding. 

Catimor 129, Costa Rica 95, IHCAFE 90, etc. are notable members of Catimor group. While Catimor group is known for its high yield and resistance to coffee leaf rust, to this date, it is generally known to produce bad quality coffee. Despite this, Catimors are considered important, especially in commercial coffee industry, as they were 'created just in time for the arrival of leaf rust in the Americas' in the 1970s.

Catimor group is not heavily present in the specialty coffee industry, or at least currently. Catimor groups are mostly grown in South East Asia and some parts of the Americas. Unless specified as single varietal coffee, it is pretty safe to assume Vietnamese Arabica, Indonesia Mandheling, etc. have some mix of Catimors. However, some argue that Catimor shouldn't be treated as inferior coffee and ['when grown with love in this part of the world, processed with care and stored appropriately, Catimor on its own or when harvested together with other varieties is more than capable of reaching the mid to high 80s in cupping sessions.'](https://indochinacoffee.com/catimor-an-intriguing-variety/) Especially with ['processing revolution'](https://sca.coffee/sca-news/watch/video/paradigm-shift-the-post-harvest-processing-revolution#:~:text=The%20current%20coffee%20processing%20revolution,and%20value%2C%20back%20to%20producers.), it seems more and more varietals that were considered 'unfavorable' are shown in different light.

### Sachimor

Sachimor is crossbreed of Villa Sarchi and Timor Hybrid. Many stable varietals are commercially available such as Parainema and Marsellesa. They are important part of the coffee industry as they have good yield, capable of producing good quality cup, resistant to various diseases and pests, and grow well in low to medium altitude. Similar to Catimors, Sachimors were also 'created just in time for the arrival of leaf rust in the Americas' in the 1970s. Parainema is primarily grown in Honduras. Marsellesa is grown in various parts of the Americas.



https://www.coffeeresearch.org/agriculture/coffeeplant.htm
https://varieties.worldcoffeeresearch.org/
https://www.cafeimports.com/australia/blog/2019/01/16/the-cafe-imports-coffee-family-tree-fourth-edition/
https://counterculturecoffee.com/blogs/counter-culture-coffee/coffee-basics-varieties
https://sca.coffee/research/coffee-plants-of-the-world
