---
title: "Understanding Terroir"
date: "`r Sys.Date()`"
tags: 
- terroir
- basics
---

# What does Terroir mean?

It literally means 'dirt' or 'earth' in French. It represents the soil, climate, altitude, and the entire environment in which the coffee plant grows. Because coffee-growing regions like Ethiopia, Colombia, Vietnam, and others all have unique environments, coffee enthusiasts can 'taste' the terroir by experiencing single-origin coffee.

Ethiopia, for example, is known for its floral aroma and complex fruit notes. Kenya is known for blackcurrant, bright acidity, and a tomato-like umami. Vietnam is famous for its earthy Robusta, while Brazil is a common choice for dark roast blends due to its nuttiness and chocolaty flavors.

I could go on listing more coffee origins and their supposed characteristics.

The truth is, I’m not sure if I believe in 'terroir' anymore.

I would like to apologize in advance, as this article is filled with subjective opinions and may come across as a bit rambly. It's a very controversial subject, and as someone who has only been interested in coffee for the past couple of years, I feel somewhat inadequate to fully address it. I considered skipping the topic altogether or simply copying generic descriptions of coffee origins, but neither option felt right. As I’ve mentioned before, I’m still an amateur. I’ll present some expert opinions both for and against the concept of terroir, along with a few of my personal thoughts. However, this article shouldn't be taken as absolute truth.

It is important to define what terroir precisely means before discussing further. I have seen many definitions that include agricultural practices, processing methods, varietal choices, and culture behind coffee agriculture. Of course, by that definition, terroir has enormous impact on coffee flavors. 

However, there are those who speak 'terroir' as some sort of mythological figure, or 'nature.' The how unique environments, provided by nature, produces distinctive flavors that cannot be found anywhere in the world.

# 'Terroir is a myth' argument

### “I don’t mean terroir is a myth as in, a falsely held belief, but rather a myth as in a way of explaining an otherwise unexplainable phenomena.” - [Maggie Harrison](https://www.wineenthusiast.com/culture/wine/is-terroir-a-myth/), Revered Oregon Winemaker

### "Myth ... is that terroir is a special property of a location something that is very special to that place" - [Lucia Solis](https://www.youtube.com/watch?v=G16gDvuQnVE), Coffee Processing Specialist

I am not claiming that the environment is not at all important. However, it seems many coffee professionals/enthusiasts believe that environments of, for example, Ethiopia is so unique that it is not possible to have similar characteristics (if not nearly identical) in Colombia, Peru, or Thailand.

However, from my personal experience, it was difficult, if not downright impossible to differentiate between a very well processed Ethiopian Gesha and a Panama Geisha. I wondered how much of the perceived differences from different origins may be due to differences in varieties, processing, and agricultural practices rather than uniqueness of the environment?

# Arguments for Terroir

Environment IS indeed important. We certainly cannot expect coffee grown in, let's say, Denmark to taste like a coffee grown in Ethiopia. We really do not have to go that far, as the coffee grown within the same farm, but from different microlots may have distinct taste. If subtle differences of micro environment can have an impact on taste, how can some argue that terroir is a myth? Is that not a clear evidence that nature plays a significant role in coffee's flavor profile?

Furthermore, there is a reason why many include processing methods as part of the terroir. Processing methods had to adapt to the local environment, because nature dictates what processing methods are viable for coffee farmers. Natural processing is particularly famous in Brazil and Ethiopia, because their low humidity climate allows farmers to use that processing method. Costa Rica, for example, had to start using Honey processing method rather than Washed processing to conserve water.

Many argue that not terroir never lost its significance, just that non-traditional processing methods have 'destroyed origin characteristics' and threaten the specialty coffee scene. While processing methods that involve other fruits or yeasts may be far more consistent, many argue that these methods destroy coffee origin characteristics and ultimately make coffee 'not special' and generic. Some extremist even argue that any coffee should be processed using ONLY water and coffee. 

# Processing Revolution and the Rise of 'Not Coffee'

### "... Processing is not irrelevant but if processing isn't creating new experiences together with that varietal then it's not interesting. Personally I fell in love with coffee because I love going to different farms, different terroirs, different climates, different countries, and experiencing all of those different tastes. It's amazing that you can go to Costa Rica and try a Gesha at 1500m and they have certain attributes versus Gesha at 1600m in Panama and those 2 copies can taste absolutely different. We don't want to make that generic through processing..." - [Patrik Rolf, founder of April Coffee and competitor of World Brewers Cup and World Barista Cup](https://www.youtube.com/watch?v=Npif5_eL1gk)

### "The coffee fruit shall be processed using pure water only." - [Cup of Excellence 2023 rule](https://perfectdailygrind.com/2023/11/cup-of-excellence-rule-changes/)

['Green coffee identity'](https://community.coffeeknowledgehub.com/rich_text_oembeds/BAh7CEkiCGdpZAY6BkVUSSI5Z2lkOi8vanVtcHN0YXJ0LWFwcC9SaWNoVGV4dE9lbWJlZC81MzcwNjE_ZXhwaXJlc19pbgY7AFRJIgxwdXJwb3NlBjsAVEkiFHJpY2hfdGV4dF9maWVsZAY7AFRJIg9leHBpcmVzX2F0BjsAVDA=--ee87b083b7c485e5c5480540c9ff971d0293714f) and the issue with ['the post-harvest processing revolution](https://www.youtube.com/watch?v=LUsAvwYFsKA) are ... definitely difficult questions. I highly recommend watching these 2 videos as I think they do a better job than I ever can. Just like Dr. Mario, I can't answer whether coffee with certain processing should be considered coffee or not.

# Worry

In my personal opinion, I think some coffee enthusiasts are worried that coffee from different origins will taste very similar due to advancement of processing, better access to different varietals, etc. They decided that the villain is the new funky processing methods and decided to label them as 'not coffee.'

I think the effort is futile. Countries like Thailand, Taiwan, Kenya, etc. are now starting to grow Gesha varietal. Countries that were previously not really interested in 'specialty coffee' like Vietnam, are now pouring more effort into processing methods, coffee varietal research, etc. Soon, people who associated Vietnam with earthy flavor or low quality will be surprised. 

Despite environment having heavy influence, clearly humans play very important roles in coffee agriculture. It is the humans that provide coffee plants with shades, fertilizer, etc. It is the humans that prunes the plants and pick the ripe coffee cherries.

### “I have two children... They came to me fully formed, they are marked by their specific DNA. And yet, I still can screw them up in 10,000 different ways, and they will spend the rest of their lives in therapy talking about all of the things I did…” - [Maggie Harrison](https://www.wineenthusiast.com/culture/wine/is-terroir-a-myth/), Revered Oregon Winemaker

# Conclusion

Sadly, there is no satisfying conclusion to any of this. It is ultimately up to you to decide. Is there something special about terroir that differentiates coffee from Ethiopia and Colombia? What processing should be allowed and shouldn't be allowed? Is 'generification' of coffee a real concern?